Feature/create
Rolling-Project/Rolling-Project pull request #15
Opened 2024-03-06 04:48 UTC by sujeong816

### Description
롤링페이퍼를 생성하는 CreateTo 컴포넌트 추가

### Changes Made
카드 배경 이미지를 우선 [타 사이트](https://picsum.photos/images)에서 받아오는 걸로 했습니다. (피그마에서 링크를 따오면 오류 발생) -추후 수정 예정

2024-03-06 07:09 UTC, suzinxix requested changes
어디까지 진행되었는지 스크린샷 올려주실 수 있으신가요??

2024-03-06 11:31 UTC, suzinxix requested changes
eslint 검사 하셨나요?! 수정님이 개발한 부분 이외는 현재 develop 브랜치에 동기화(?)한 후 머지 해야할 것 같습니다!

2024-03-06 11:31 UTC, suzinxix commented on .prettierrc.js
> +  jsxSingleQuote: true, // JSX에 작은 따옴표 사용 여부
현재 develop 브랜치에 `jsxSingleQuote: false,`로 되어 있습니다! 변경해주세요!

2024-03-06 11:31 UTC, suzinxix commented on .prettierrc.js
> +  trailingComma: "none" // 후행 쉼표 설정
```
  trailingComma: 'none', // 후행 쉼표 설정
  jsxSingleQuote: false
```
작은 따옴표로 변경해주세요!

2024-03-06 11:31 UTC, suzinxix commented on package.json
> +    "eslint": "^8.57.0",
버전 혹시 변경하신건가요?!

2024-03-06 11:31 UTC, suzinxix commented on src/App.jsx
> +import { BrowserRouter as Router } from 'react-router-dom'; // BrowserRouter 임포트
라우터는 라우터 폴더에서 관리하고 있어서 import 빼주셔도 돼요!

2024-03-06 11:31 UTC, suzinxix commented on src/Routers/Routers.jsx
> +      <Route path='/post/:id' element={<RollingPaper />} />
작은 따옴표로 path 설정했을 때 에러 안나셨어요?!

2024-03-08 04:48 UTC, sujeong816 commented on .prettierrc.js
> +  jsxSingleQuote: true, // JSX에 작은 따옴표 사용 여부
변경 완료했습니다.

2024-03-08 04:48 UTC, sujeong816 commented on .prettierrc.js
> +  trailingComma: "none" // 후행 쉼표 설정
변경 완료했습니다.

2024-03-08 04:49 UTC, sujeong816 commented on package.json
> +    "eslint": "^8.57.0",
지웠다가 재설치했더니 자동으로 버전이 바뀌었나봐요!
develop 버전으로 다시 설정했습니다

2024-03-08 04:50 UTC, sujeong816 commented on src/App.jsx
> +import { BrowserRouter as Router } from 'react-router-dom'; // BrowserRouter 임포트
제 로컬에서는 Router로 한 번 감싸줘야 에러가 안 나더라구요ㅠㅠ Router를 빼면 에러로 화면이 안 뜹니다!!

2024-03-08 04:51 UTC, sujeong816 commented on src/Routers/Routers.jsx
> +      <Route path='/post/:id' element={<RollingPaper />} />
jsx 설정 때문에 그런가 오류는 안 났는데, 일단 큰 따옴표로 수정했습니다!

2024-03-08 06:51 UTC, closed without merging